name: Docker Test
on:
    workflow_dispatch:
    push:
      branches:
        - main
    pull_request:

jobs:
  docker-test:
    name: Run imhost on Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker pull golang:alpine
          docker compose -f ./.github/docker-compose-test.yml up --build -d

      - name: Test request
        run: |
          curl -sS http://localhost:8080/ | grep Hello\ from\ host

      - name: Tear down Docker
        run: |
          docker compose -f ./.github/docker-compose-test.yml down --remove-orphans
          docker system prune -af
