# This workflow is triggered manually. It is used to test the
# functionality of the already released Dockerfile.
name: Example Functionality Test
on:
    workflow_dispatch:

jobs:
  example-test:
    name: Test docker compose scaling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run the example
        run: |
          cd _example
          ./up.sh 10
