name: GolangCI
on:
    workflow_dispatch:
    push:
      branches:
        - main
    pull_request:

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      # Linting and static analysis
      - uses: golangci/golangci-lint-action@v4
        with:
          version: latest
